name: UrlCommands
main: com.ne0nx3r0.UrlCommands.UrlCommands
version: '0.2'
database: false
description: Command based URL calls
depend: [UrlManager]
commands:
   uc:
      description: Calls a defined URL call